# Generated by Django 3.2.9 on 2021-11-16 11:57

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='blocks',
            field=wagtail.core.fields.StreamField([('simple_question', wagtail.core.blocks.StructBlock([('extended_answer', wagtail.core.blocks.StructBlock([('body', wagtail.core.blocks.StreamBlock([('text', wagtail.core.blocks.RichTextBlock())]))]))]))], default=list),
            preserve_default=False,
        ),
    ]
